# Generated by Django 3.1.7 on 2021-04-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_profile_second_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='D:\\Personalized_meal_recommendation_system-master\\DJANGO\\minor\\media\\website\\images\\avtar.png', upload_to='website/images'),
        ),
    ]
